
[font]
size = 12.0

[font.bold]
#family = "Fira Code"
family = "Monocraft"
style = "Bold"

[font.bold_italic]
family = "Monocraft"
style = "Bold Italic"

[font.italic]
family = "Monocraft"
style = "Italic"

[font.normal]
family = "Monocraft"

[general]
import = ["/home/connor/.config/alacritty/hyper.toml"]
